config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'groups/index'
  get 'groups/show'
  get 'groups/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  devise_for :persons, :controllers => {sessions: "sessions"}

  resources :persons do
    resources :groups
  end

  resources :groups do
    resources :posts
    member do
      post :join
      delete :leave
      post :user_approved
      post :user_banned
      post :user_muted
      post :manage_user
      post :post_approved
      post :post_unreport
    end
  end

  resources :persons do
  	resources :posts
    member do
      get 'profile'
      get 'overview'
      get 'comments'
      get 'saved'
      get 'saved'
      get 'hidden'
      get 'upvoted'
      get 'upvoted'
      get 'downvoted'
      get 'all_settings'
      get 'account'
      post 'account_setting'
      get 'person_profile'
      post 'profile_setting'
      get 'feed'
      post 'feed_setting'
      post 'follow'
      post "post_options"
      post 'report_post'
    end
  end

  resources :posts do
  	resources :comments
    member do
      post 'vote'
    end
  end

  resources :posts do
    resources :comments
  end

  resources :comments do
    member do
      post 'vote'
      post 'report'
    end
    collection do
      post "reply"
    end
  end

  resources :replies do
    member do
      post 'vote'
    end
  end

  get "/search", to: "home#search"
  get "/alert", to: "home#alert"
  get "/list_categories", to: "home#list_categories"

  namespace :admin do
    devise_for :admins, skip: :registrations
    root to: "admins#index"
    resources :persons, only: [:index, :show, :destroy] do
      collection do
        get 'person_index'
      end
    end
    resources :groups, only: [:index, :show, :destroy] do
      collection do
        get 'group_index'
      end
    end
    resources :posts, only: [:index, :show, :destroy] do
      collection do
        get 'post_index'
      end
    end
    resources :comments, only: [:index, :show, :destroy] do
      collection do
        get 'comment_index'
      end
    end
    resources :categories do
      collection do
        get 'category_index'
      end
    end
  end
end

app/models/comment.rb
class Comment
	include Neo4j::ActiveNode
	property :content, type: String
	property :created_at, type: DateTime
	property :updated_at, type: DateTime
  	property :upvotes, type: Integer,  default: 0
  	property :downvotes, type: Integer,  default: 0

  	id_property :id, auto: :uuid

	has_one :out, :post, type: :comment_on
	has_one :out, :author, type: :author, model_class: :Person
	has_many :in, :replies, type: :reply_on, model_class: :Comment, dependent: :destroy
  	has_many :in, :upvote, type: :upvoted_by, model_class: :Person
  	has_many :in, :downvote, type: :downvoted_by, model_class: :Person

	enum type: [:comment, :reply], _default: :comment

  	def votes
    	self.upvotes - self.downvotes
  	end

	def to_pretty
    	a = (Time.now-self.created_at).to_i
	    case a
	      when 0 then 'just now'
	      when 1 then 'a second ago'
	      when 2..59 then a.to_s+' seconds ago'
	      when 60..119 then 'a minute ago' #120 = 2 minutes
	      when 120..3540 then (a/60).to_i.to_s+' minutes ago'
	      when 3541..7100 then 'an hour ago' # 3600 = 1 hour
	      when 7101..82800 then ((a+99)/3600).to_i.to_s+' hours ago'
	      when 82801..172000 then 'a day ago' # 86400 = 1 day
	      when 172001..518400 then ((a+800)/(60*60*24)).to_i.to_s+' days ago'
	      when 518400..1036800 then 'a week ago'
	      else ((a+180000)/(60*60*24*7)).to_i.to_s+' weeks ago'
	    end
	end

  def add_upvote person
    person.upvote_comment << self
    self.upvote << person
    self.update_column :upvotes, 1
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  before_action :get_comment
  def index
    page = params[:page] ? (params[:page].to_i * 25) : 25
    @comments = Comment.all
    @load_more = @comments.length > page ? true : false
    @comments = @comments.limit(page)
  end
  def show
  end

  def comment_index
    page = params[:page] ? (params[:page].to_i * 25) : 25
    if params[:post_id]
      @post = Post.find_by(id: params[:post_id])
      @all_comments = @post.comments
    end
    @load_more = @all_comments.length > page ? true : false
    @comments = @all_comments.limit(page)

  end
  def destroy
    @comment.destroy
    redirect_to admin_comment_path()
  end
  private
  def get_comment
    return if params[:id].nil?
    @comment = Comment.find_by(id: params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_comment, :get_post
	def index
		@post = Post.find(params[:post_id])
		@comment = @post.comments.all
	end

	def new
		@post = Post.find(params[:id])
		@comment = @post.comments.new
	end

	def create
		@post = Post.find(params[:post_id])
    @group = @post.belong_to
    if @group && @group.muted_members.include?(current_person)
      @message = "You have been MUTED in this group!"
      respond_to do |format|
        format.html
        format.js {render "home/alert"}
      end
    else
  		@comment = Comment.create!(params_comment)
  		@post.comments << @comment
  		current_person.comments << @comment
      @comment.add_upvote(current_person)
      @new_reply = Comment.new
      @list_post_comments = @post.comments.where(type: :comment)
      respond_to do |format|
        format.html
        format.js
      end
    end
	end

  def vote
    return unless params[:vote]
    if @comment.upvote.include?(current_person) || @comment.downvote.include?(current_person)
      if @comment.upvote.include?(current_person) && params[:vote] == "downvote"
          # post
          @comment.upvotes -= 1
          @comment.upvote.delete(current_person)
          @comment.downvotes += 1
          @comment.downvote << current_person
          @color = 'purple'
          # person
          current_person.upvote_comment.delete(@comment)
          current_person.downvote_comment << @comment
        elsif @comment.downvote.include?(current_person) && params[:vote] == "upvote"
          @comment.downvotes -= 1
          @comment.downvote.delete(current_person)
          @comment.upvotes += 1
          @comment.upvote << current_person
          # person
          current_person.upvote_comment << @comment
          current_person.downvote_comment.delete(@comment)
          @color = "red"
        elsif @comment.upvote.include?(current_person) && params[:vote] == "upvote"
          @comment.upvotes -= 1
          @comment.upvote.delete(current_person)
          current_person.upvote_comment.delete(@comment)
          @color = "none"
        else
          @comment.downvotes -= 1
          @comment.downvote.delete(current_person)
          current_person.downvote_comment.delete(@comment)
          @color = "none"
      end
    else
      if params[:vote] == "upvote"
        @comment.upvotes += 1
        @comment.upvote << current_person
        current_person.upvote_comment << @comment
        @color = "red"
      else
        @comment.downvotes += 1
        @comment.downvote << current_person
        current_person.downvote_comment << @comment
        @color = 'purple'
      end
    end
    @comment.save!
    current_person.save!
    respond_to do |format|
      format.html
      format.js
    end
  end

  def reply
    @comment = Comment.create!(params_comment.merge(type: :reply))
    @parent_comment = Comment.find(params[:comment_id])
    @parent_comment.replies << @comment
    current_person.comments << @comment
    @comment.add_upvote(current_person)
    @comment.post = @post
    @new_reply = Comment.new
    respond_to do |format|
      format.html
      format.js {render :replies}
    end
  end

  def report
    
  end
	private

  def get_post
    return unless params[:post_id]
    @post = Post.find(params[:post_id])
  end

  def get_comment
    @comment = Comment.find_by(id: params[:id])
  end

	def params_comment
		params.require(:comment).permit(:content)
	end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_body.html.slim
.comment-post
  .comment-parent.display-flex.comment-post-box
    .comment-voted
      = link_to vote_comment_path(comment, vote: :upvote, view: "index"), method: :post, remote: true do
        .mb5 = fa_icon "arrow-up", class:"#{comment.upvote.include?(current_person) ? 'upvoted' : ""}"
      = link_to vote_comment_path(comment, vote: :downvote, view: "index"), method: :post, remote: true do
        = fa_icon "arrow-down", class:"#{comment.downvote.include?(current_person) ? 'downvoted' : ""}"
    .body-comment-parent
      . id="#{comment.id}"
        .body-comment.display-flex.mb5
          .user.user-email.mr5.s12 = link_to person.email, overview_person_path(person), class: "c_gray"
          - if comment.author == current_person
            .mr5
              = fa_icon "microphone", class:"c_0079d3"
          .tc
            span.dot
          .comment-votes.s12.mr5 ="#{comment.votes} point"
          .tc
            span.dot
         	span.tmol.s12.c_gray = comment.to_pretty
        .comment-text class="#{type == 'comment' ? 'mb5' : 'mb15'}"
        	= content
        = render partial: 'comments/comment_option', locals: {type: "comment", comment: comment}
        = render partial: "replies/reply_comment", locals: {new_reply: new_reply, comment: comment, post: comment.post}
  	  .list-comment-reply
				= render partial: "comments/reply_body", locals: {comment: comment, new_reply: new_reply}

app/views/comments/_comment_option.html.slim
.comment-option.mt5.mb10
  - if type == 'comment'
    #reply.option-style
      span = fa_icon "comment"
      span Reply
  - else
    #reply-comment.option-style
      span = fa_icon "comment"
      span Reply
  .share.option-style
    span Share
  - if comment.author == current_person
    .edit-post.option-style
      span Edit
  .save.option-style
    - if current_person
        span#save-post Save
    - else
      = link_to alert_path(message: "You need sign up first to do this action!"), remote: true do
        span#save-post Save
  - unless @comment.author == current_person
    .report.option-style
      - if current_person
        = link_to report_comment_path(comment), method: :post do
          span Report
      - else
        = link_to alert_path(message: "You need sign up first to comment!"), remote: true do
          span Report

app/views/comments/_index.html.slim
- @post.comments.each do |cm|
	p Content
	= cm.content
	hr

app/views/comments/_list_comments.html.slim
- comments.each do |comment|
	.comment-user
		= render partial: "comments/comment_body", locals: {person: comment.author, content: comment.content, data: comment, type: "comment", new_reply: new_reply, comment: comment}
	hr

app/views/comments/_new_comment.html.slim
.box_form_comment.form-group
  - if person_signed_in?
  	= form_for @comment, url: post_comments_path(@post), remote: true  do |cm|
  	  	.comment.mb10
  	  		span.comment-as
  	  			| Comment as
  	  			= link_to current_person.email, overview_person_path(current_person), class:'ml5'
    	 	.mb10 = cm.text_area :content, placeholder: "Please comment here", class: "form-control", required: true
        .row
            .col-md-9
            .col-md-3.col-md-offset-3
      	 	  	= cm.submit "Comment", class: "btn btn-create btn-submit-comment float-right"
  - else
   .row.mtb20.border
      .col-md-7.tmol.p10
        span.tmol.c_gray.s18 What are your thoughts? Log in or Sign up
      .col-md-5.p10
        = link_to "Sign up", new_person_registration_path(), class: "btn btn-signup float-right"
        = link_to "login", person_session_path(), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-login'}

app/views/comments/_reply_body.html.slim
- comment.replies.each do |reply|
  .reply.display-flex.comment-post-box
    .comment-voted
      = link_to vote_comment_path(reply, vote: :upvote, view: "index"), method: :post, remote: true do
        .mb5 = fa_icon "arrow-up", class:"#{reply.upvote.include?(current_person) ? 'upvoted' : ""}"
      = link_to vote_comment_path(reply, vote: :downvote, view: "index"), method: :post, remote: true do
        = fa_icon "arrow-down", class:"#{reply.downvote.include?(current_person) ? 'downvoted' : ""}"
    .body-reply-comment
      . id="#{reply.id}"
        .body-comment.tmol.mb5

          .user.user-email.mr5.s12 = link_to reply.author.email, overview_person_path(reply.author), class: "c_gray"
          - if reply.author == current_person
            .mr5
              = fa_icon "microphone", class:"c_0079d3"
          .tc
            span.dot
          .comment-votes.s12.mr5 ="#{reply.votes} point"
          .tc
            span.dot
          span.tmol.s12.c_gray = reply.to_pretty
        .comment-text class="'mb15"
          = reply.content
        = render partial: 'comments/comment_option', locals: {type: "reply", comment: reply}
        = render partial: "replies/reply_comment", locals: {new_reply: new_reply, comment: reply, post: comment.post}
        .list-comment-reply
            = render partial: "comments/reply_body", locals: {comment: reply, new_reply: new_reply}

app/views/comments/create.js.erb
$("#comment_content").val("")
$(".list-comment").html("<%=j render :partial => 'comments/list_comments', locals: {comments: @list_post_comments, new_reply: @new_reply} %>");
$(".post-option").html("<%=j render :partial => 'home/post_option', locals:{post: @post} %>");

app/views/comments/new.html.slim
= render partical: "comment", locals: {comment: @comment, post: @post} 

app/views/comments/replies.js.erb
$("#<%= @parent_comment.id%>").find(".box_form_comment").first().css("display", "none");
$("#<%= @parent_comment.id%>").find(".box_form_comment").first().find("#comment_content").val("");
$("#<%= @parent_comment.id%>").find(".list-comment-reply").first().html("<%=j render :partial => 'comments/reply_body', locals: { comment: @parent_comment, new_reply: @new_reply, type: 'comment' } %>");

app/views/comments/vote.js.erb
<% if @view = "index" %>
  $("#<%= @comment.id %>").find(".comment-votes").first().text("<%=@comment.votes%> points");
  <% case @color %>
  <% when "red" %>
    $("#<%= @comment.id %>").closest(".comment-post-box").find(".downvoted").removeClass("downvoted");
    $("#<%= @comment.id %>").closest(".comment-post-box").find(".fa-arrow-up").first().addClass("upvoted");
  <% when "purple" %>
    $("#<%= @comment.id %>").closest(".comment-post-box").find(".upvoted").removeClass("upvoted")
    $("#<%= @comment.id %>").closest(".comment-post-box").find(".fa-arrow-down").first().addClass("downvoted");
  <% when "none" %>
    $("#<%= @comment.id %>").closest(".comment-post-box").find(".upvoted").removeClass("upvoted")
    $("#<%= @comment.id %>").closest(".comment-post-box").find(".downvoted").removeClass("downvoted");
  <% end %>
<% end %>