config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'groups/index'
  get 'groups/show'
  get 'groups/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  devise_for :persons, :controllers => {sessions: "sessions"}

  resources :persons do
    resources :groups
  end

  resources :groups do
    resources :posts
    member do
      post :join
      delete :leave
      post :user_approved
      post :user_banned
      post :user_muted
      post :manage_user
      post :post_approved
      post :post_unreport
    end
  end

  resources :persons do
  	resources :posts
    member do
      get 'profile'
      get 'overview'
      get 'comments'
      get 'saved'
      get 'saved'
      get 'hidden'
      get 'upvoted'
      get 'upvoted'
      get 'downvoted'
      get 'all_settings'
      get 'account'
      post 'account_setting'
      get 'person_profile'
      post 'profile_setting'
      get 'feed'
      post 'feed_setting'
      post 'follow'
      post "post_options"
      post 'report_post'
    end
  end

  resources :posts do
  	resources :comments
    member do
      post 'vote'
    end
  end

  resources :posts do
    resources :comments
  end

  resources :comments do
    member do
      post 'vote'
      post 'report'
    end
    collection do
      post "reply"
    end
  end

  resources :replies do
    member do
      post 'vote'
    end
  end

  get "/search", to: "home#search"
  get "/alert", to: "home#alert"
  get "/list_categories", to: "home#list_categories"

  namespace :admin do
    devise_for :admins, skip: :registrations
    root to: "admins#index"
    resources :persons, only: [:index, :show, :destroy] do
      collection do
        get 'person_index'
      end
    end
    resources :groups, only: [:index, :show, :destroy] do
      collection do
        get 'group_index'
      end
    end
    resources :posts, only: [:index, :show, :destroy] do
      collection do
        get 'post_index'
      end
    end
    resources :comments, only: [:index, :show, :destroy] do
      collection do
        get 'comment_index'
      end
    end
    resources :categories do
      collection do
        get 'category_index'
      end
    end
  end
end

app/models/group.rb
class Group
	include Neo4j::ActiveNode

	id_property :id, auto: :uuid

	property :group_name
  	property :about, type: String
  	property :them, type: String
  	property :text_color, type: String

  	property :icon, type: String
  	mount_uploader :icon, GroupBannerUploader
  	property :banner, type: String
  	mount_uploader :banner, GroupIconUploader

	property :created_at, type: DateTime
	property :updated_at, type: DateTime

	has_one :out, :author, type: :create_by, model_class: :Person
	has_many :in, :members, type: :joins, model_class: :Person, dependent: :destroy
	has_many :in, :unapprove_members, type: :unapprove, model_class: :Person, dependent: :destroy
	has_many :in, :banned_members, type: :banned, model_class: :Person, dependent: :destroy
	has_many :in, :muted_members, type: :muted, model_class: :Person, dependent: :destroy
	has_many :in, :posts, origin: :belong_to, dependent: :destroy
	  has_many :in, :unapprove_posts, type: :unapprove_post, model_class: :Post, dependent: :destroy

  enum type: [:public, :restricted, :private], _default: :public

  after_create :add_first_post
  after_create :add_default_icon

	def check_color
		self.text_color.present? ? self.text_color : '_0079d3'
	end

	def check_them
		self.them.present? ? self.them : '_0079d3'
	end

	def check_view mode_view, params
		if mode_view == params
			self.text_color.present? ? self.text_color : '_0079d3'
		else
			"gray"
		end
	end

  	def add_first_post
    	title = "#{self.group_name} has been created"
    	content = self.about
    	person = self.author
    	post = Post.create!(title: title, content: content, post_creation: true)
    	post.upvotes += 1
    	post.upvote << person
    	person.posts << post
    	self.posts << post
  	end

	def add_default_icon
		File.open('public/group-icon.jpeg') do |f|
	  		self.icon = f
		end
		self.save!
	end

end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::ApplicationController
  before_action :get_group
  def index
    page = params[:page] ? (params[:page].to_i * 25) : 25
    @groups = Group.all
    @load_more = @groups.length > page ? true : false
    @groups = @groups.limit(page)
  end

  def show
  end

  def group_index
    page = params[:page] ? (params[:page].to_i * 25) : 25
    if params[:person_id]
      @person = Person.find_by(id: params[:person_id])
      @all_groups = @person.join_groups
    end
    @load_more = @all_groups.length > page ? true : false
    @groups = @all_groups.limit(page)
  end

  def destroy
    @group.destroy_all
    redirect_to admin_groups_path()
  end
  private
  def get_group
    @group = Group.find_by(id: params[:id])
  end
end
  

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  layout "groups"
  before_action :get_group
  def index
  	@groups = Group.all
  end

  def show
    @post = @group.posts.new
    @comment = @post.comments.new
    @reply = @comment.replies.new
    @posts = @group.posts.all
    case params[:order_sort]
    when 'new'
      @posts = @posts.sort { |x, y | y.created_at <=> x.created_at }
    when 'most_commentted'
      @posts = @posts.sort { |x, y | y.comments.count <=> x.comments.count }
    when 'most_voted'
      @posts = @posts.sort { |x, y | x.total_votes <=> y.total_votes }
    else
      @posts = @posts.sort { |x, y | y.best_post? <=> x.best_post? }
    end
    case params[:view]
    when 'posts'
    when 'about'
    when 'members'
      members = @group.members
    end
    respond_to do |format|
      format.html
      format.js {render :index}
    end
  end

  def edit
    @posts = @group.unapprove_posts
    case params[:option]
    when 'mod_queue'
      @posts = @group.unapprove_posts
    when 'unpprove_posts'
      @posts = @group.unapprove_posts
    when 'report'
      @posts = @group.posts.select {|x| x.reports}
    when 'approved'
      @unapprove_members = @group.unapprove_members
    when 'members'
      @members = @group.members.select {|x| !x.groups.include?(@group)}
    when 'banned'
      @members = @group.banned_members
    when 'muted'
      @members = @group.muted_members
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
  	@group = current_person.groups.new
    render layout: 'persons'
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
  	@group = Group.new(group_params)
    @group.icon = group_params[:icon] if group_params[:icon].present?
    @group.banner = group_params[:banner] if group_params[:banner].present?
  	@group.author = current_person
    @group.members << current_person
    @group.save!
  	redirect_to group_path(@group)
  end

  def join
    if @group.type == :private
      if @group.unapprove_members.include?(current_person)
        btn_label =
        @group.unapprove_members.delete(current_person)
      else
        @group.unapprove_members << current_person
      end
    else
      if @group.members.include?(current_person)
       @group.members.delete(current_person)
        current_person.join_groups.delete(@group)
      else
    	 @group.members << current_person
        current_person.join_groups << @group
      end
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def leave
    if @group.author == current_person
      @message = "You are the Leader of this Community. Cannot leave!"
      respond_to do |format|
        format.html
        format.js {render "home/alert"}
      end
    else
      @group.members.delete current_person
      current_person.join_groups.delete(@group)
      respond_to do |format|
        format.html
        format.js {render :join}
      end
    end
  end

  def user_approved
    @person = Person.find_by(id: params[:person_id])
    @group.unapprove_members.delete(@person)
    @group.members << @person
    params[:option] = 'approved'
    @unapprove_members = @group.unapprove_members
    respond_to do |format|
        format.html
        format.js {render :edit}
    end
  end

  def manage_user
    @person = Person.find_by(id: params[:person_id])
    case params[:option]
    when 'ban'
      if @group.banned_members.include?(@person)
        @group.banned_members.delete @person
      else
        @group.banned_members << @person
      end
    when "mute"
      if @group.muted_members.include?(@person)
        @group.muted_members.delete @person
      else
        @group.muted_members << @person
      end
    end
    @members = @group.members.select {|x| !x.groups.include?(@group)}
    params[:option] = 'members'
    respond_to do |format|
      format.html
      format.js {render :edit}
    end
  end

  def user_banned
    @person = Person.find_by(id: params[:person_id])
    if @group.banned_members.include?(@person)
      @group.banned_members.delete @person
    else
      @group.banned_members << @person
    end
    @members = @group.banned_members
    respond_to do |format|
      format.html
      format.js {render}
    end
  end

  def user_muted
    @person = Person.find_by(id: params[:person_id])
    if @group.muted_members.include?(@person)
      @group.muted_members.delete @person
    else
      @group.muted_members << @person
    end
    @members = @group.muted_members
    respond_to do |format|
      format.html
      format.js {render}
    end
  end

  def post_approved
    @post = Post.find_by(id: params[:post_id])
    if @group.unapprove_posts.include?(@post)
      @group.unapprove_posts.delete(@post)
      @group.posts << @post
      @post.reports.map do |x|
        x.destroy if x.type == "user_report"
      end
      @post.reports = []
      @post.save
    else
      @group.unapprove_posts << (@post)
      @group.posts.delete @post
    end
    redirect_to request.referrer
  end

  def post_unreport
    @post = Post.find_by(id: params[:post_id])
    @post.reports.map do |x|
      x.destroy if x.type == "user_report"
    end
    @post.reports = []
    @post.save
    redirect_to request.referrer
  end

  private
  def get_group
    return unless params[:id]
    @group = Group.find(params[:id])
  end
  def group_params
  	params.require(:group).permit(:group_name, :about, :icon, :banner, :them, :text_color, :type)
  end
  def post_params
    params.require(:post).permit(:title, :content, :image)
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group_info.html.slim
.group-box-info#group-box-info
  .group-header.tmol id="#{group.check_them}"
    .title COMMUNITY DETAILS
    - if current_person && group.author == current_person
      = link_to edit_group_path(group), class:"c_white tmol" do
        = fa_icon "shield", class:"c_white mr5"
        .s12.tb700 Mod Tools
  .group-info
    #info.tmol
      .group-icon
        - if group.icon.present?
          = image_tag group.icon_url
      .title.il.l10
        = group.group_name
    .info
      .row
        .col-md-6.border-right
          .tb = group.members.count
          .s12 Members
        .col-md-6
          .tb = group.posts.count
          .s12 Posts
    .type-group.mt5
      - if group.type == :private
        = fa_icon "lock", class:"mr10 c_fd7e14"
        span Private
      - elsif group.type == :public
        = fa_icon "user", class:" mr10 c_17a2b8"
        span Public
      - else
        = fa_icon "eye", class:"ml10 mr10 c_104939"
        span Restricted
    .box-content.mb5
      span.s15 = group.about
    .box-btn
      - if person_signed_in?
        - if group.members.include?(current_person)
          = link_to "JOINED", leave_group_path(group), method: :delete , remote: true, class: "btn btn-joined mb10"
        - elsif group.unapprove_members.include?(current_person)
          = link_to "REQUEST SENDED", join_group_path(group), method: :post, remote:true, class: "btn btn-join-group bi#{group.check_color} mb10"
        - else
          = link_to "JOIN", join_group_path(group), method: :post, remote:true, class: "btn btn-join-group bi#{group.check_color} mb10"
        - if group.members.include?(current_person) || group.type == :public 
          = link_to "CREATE POST", new_group_post_path(group), class: "btn btn-create-post bi#{group.check_color}"
      - else
        = link_to "JOIN", person_session_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: "btn btn-join-group bi#{group.check_color} mb10"}
        = link_to "CREATE POST", person_session_path(), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: "btn btn-create-post bi#{group.check_color}"}

app/views/groups/_group_members.html.slim
.white.p10
  - group.author
    .mod-header.mb10
      span Leader
      .
        span.mr5 Full Name:
        = group.author&.full_name
      .
        span.mr5 Email:
        = link_to group.author&.email, overview_person_path(group.author)
      .
        span.mr5 Contact:
  .mod-header
  	span Members
  br
  - if @group.members.any?
    table class="table table-striped white" data-sort-name="name" data-sort-order="desc"
      thead
        tr
          th data-field="age" data-sortable="true" Full Name
          th data-field="name" data-sortable="true" Email
      tbody
        - @group.members.each do |person|
          tr
            td = person.full_name
            td style="width: 33%"
              = link_to person.email, overview_person_path(person)
  - else
    .empty
      .description
        = fa_icon "user-times" , class: "mb10"
        .s18.tb700.c_gray There's no unapprove members!
  	    = render partial: 'group_members', locals: {persons: @members}
      .col-md-1

app/views/groups/_list_muted_user.html.slim
- if persons.any?
  table class="table-bordered table table-striped white" data-sort-name="name" data-sort-order="desc"
    thead
      tr
        th data-field="name" data-sortable="true" Email
        th data-field="age" data-sortable="true" Full Name
        th data-field="age" data-sortable="true" Status
        th data-field="age" Action
    tbody
      - persons.each do |person|
        tr
          td style="width: 33%"
            = link_to person.email, overview_person_path(person)
          td = person.full_name
          td
            - if @group.banned_members.include?(person)
              .action-admin.il._ffc107.tb.c_white Banned
            - if @group.muted_members.include?(person)
              .action-admin.il._940bdd.tb.c_white Muted
          td
            .admin-action
              .action-admin.il class="_red"
                = link_to admin_person_path(person), method: :delete, data: {confirm: "Are you sure?"} do
                  span Remove
              .action-admin.il.btn-ban
                = link_to "#{@group.muted_members.include?(person) ? 'Unmute' : 'Mute'}", user_muted_group_path(@group, person_id: person.id, option: 'mute'), method: :post, remote: true, class:"tb"
- else
  .empty
    .description
      = fa_icon "window-close" , class: "mb10"
      .s18.tb700.c_gray There's no members muted!

app/views/groups/_list_user.html.slim
- if persons.any?
  table class="table-bordered table table-striped" data-sort-name="name" data-sort-order="desc"
    thead
      tr
        th data-field="name" data-sortable="true" Email
        th data-field="age" data-sortable="true" Full Name
        th data-field="age" data-sortable="true" Posts
        th data-field="age" Action
    tbody
      - persons.each do |person|
        tr
          td style="width: 33%"
            = link_to person.email, overview_person_path(person)
          td = person.full_name
          td
            = link_to post_index_admin_posts_path(person_id: person.id) do
              = "#{person.posts.count} posts"
          td
            .admin-action
              .action-admin.il class="_red"
                = link_to admin_person_path(person), method: :delete, data: {confirm: "Are you sure?"} do
                  span Remove
              .action-admin.il class="_28a745"
                = link_to 'Approve', user_approved_group_path(@group, person_id: person.id), method: :post, remote: true
- else  
  p There no unapprove members

app/views/groups/_manage_user.html.slim
- if persons.any?
  table class="table-bordered table table-striped white" data-sort-name="name" data-sort-order="desc"
    thead
      tr
        th data-field="name" data-sortable="true" Email
        th data-field="age" data-sortable="true" Full Name
        th data-field="age" data-sortable="true" Status
        th data-field="age" Action
    tbody
      - persons.each do |person|
        tr
          td style="width: 33%"
            = link_to person.email, overview_person_path(person)
          td = person.full_name
          td
            - if @group.banned_members.include?(person)
              .action-admin.il._ffc107.tb.c_white Banned
            - if @group.muted_members.include?(person)
              .action-admin.il._940bdd.tb.c_white Muted
            - elsif !@group.banned_members.include?(person) && !@group.muted_members.include?(person)
              .action-admin.il._28a745.tb.c_white Approved
          td
            .admin-action
              .action-admin.il class="_red"
                = link_to admin_person_path(person), method: :delete, data: {confirm: "Are you sure?"} do
                  span Remove
              .action-admin.il.btn-ban
                = link_to "#{@group.banned_members.include?(person) ? 'Unban': 'Ban'}", manage_user_group_path(@group, person_id: person.id, option: 'ban'), method: :post, remote: true, class:"tb"
              .action-admin.il.btn-ban
                = link_to "#{@group.muted_members.include?(person) ? 'Unmute' : 'Mute'}", manage_user_group_path(@group, person_id: person.id, option: 'mute'), method: :post, remote: true, class:"tb"
- else
  p There's no members

app/views/groups/_muted_members.html.slim
.container-fluid
  .row
    .col-md-1
    .col-md-10
      .mod-header
        span User Muted
        .back-to-group.il.float-right
          = link_to "Back to #{@group.group_name}", person_group_path(current_person, @group), class:" btn"

      br
      .chec-box-list.white.mb10.display-flex
        = check_box :all, nil, class:'bigger-checkbox m10'
        .tmol.mr10 = fa_icon 'sort-desc'
            #tool-option.display-flex.display-none
            .approve.tmol.mr10
              .mr5 = fa_icon 'check'
              span.s12.tb700 Approve
            .remove.tmol.mr10
              .mr5 = fa_icon 'trash'
              span.s12.tb700 Remove
            .remove.tmol.mr10
              .mr5 = fa_icon 'window-close'
              span.s12.tb700 Spam
      = render partial: 'list_muted_user', locals: {persons: @members}
    .col-md-1

app/views/groups/_post_status.html.slim
br
  .group-box-info
    .group-header.tmol
      .title POST STATUS
    .trending-communities
    	.person-status
			.message
				span.mr5 This post have these reports:
				ul
					- if spam_post = post.reports.select {|x| x.type == "spam"} 
						- if !spam_post.blank?
							li.s12.tb.c_red = "It's a Spam (#{spam_post.count})"
					- if copyright_post = post.reports.select {|x| x.type == "copyright"} 
						- if !copyright_post.blank?
							li.s12.tb.c_red = "#{copyright_post.last.content} (#{copyright_post.count})"
					- if harassment_post = post.reports.select {|x| x.type == "harassment"} 
						- if !harassment_post.blank?
							li.s12.tb.c_red = "#{harassment_post.last.content} (#{harassment_post.count})"
					- if rude_post = post.reports.select {|x| x.type == "rude"} 
						- if !rude_post.blank?
							li.s12.tb.c_red = "#{rude_post.last.content} (#{rude_post.count})"
					- if sex_post = post.reports.select {|x| x.type == "sex"} 
						- if !sex_post.blank?
							li.s12.tb.c_red = "#{sex_post.last.content} (#{sex_post.count})"
					- if user_report_post = post.reports.select {|x| x.type == "user_report"} 
						- user_report_post.each do |report|
							li.s12.tb.c_red = "#{report.content}"

app/views/groups/_report_posts.html.slim
.container-fluid
  .row
    .col-md-1
    .col-md-10
      .mod-header
        span Posts Report
        .back-to-group.il.float-right
          = link_to "Back to #{@group.group_name}", person_group_path(current_person, @group), class:" btn"
      br
    	.chec-box-list.white.mb10.display-flex
	    	= check_box :all, nil, class:'bigger-checkbox m10'
	    	.tmol.mr10 = fa_icon 'sort-desc'
            #tool-option.display-flex.display-none
    	    	.approve.tmol.mr10
    	    		.mr5 = fa_icon 'check'
    	    		span.s12.tb700 Approve
    	    	.remove.tmol.mr10
    	    		.mr5 = fa_icon 'trash'
    	    		span.s12.tb700 Remove
    	    	.remove.tmol.mr10
    	    		.mr5 = fa_icon 'window-close'
    	    		span.s12.tb700 Spam
	    = render partial: 'list_post/posts_reported', locals: {posts: @posts}

    .col-md-1

app/views/groups/_sort_bar.html.slim
.sort-bar-header
	.sort-bar.tmol
		span VIEW
		= link_to group_path(@group, view: "large", order_sort: order_sort), remote:true do
			- active = "#{@group.check_view('large', view)}"
			.view-large
				table
					tr.line-split class="#{active}"
						td
					tr class="#{active}"
						td
		= link_to group_path(@group, view: "medium", order_sort: order_sort), remote: true do
			- active = "#{@group.check_view('medium', view) }"
			.view-medium
				table
					tr.line-split class="#{active}"
						td
					tr.line-split class="#{active}"
						td
					tr class="#{active}"
						td

		span style="margin-left: 30px;" SORT
		.btn-group#group-sort-btn
          button.btn.dropdown-toggle.user-info data-toggle="dropdown"
          	- order = order_sort ? order_sort : 'best'
          	- value = SORT_PARAMS[order.to_sym]
          	span.icon-profile = fa_icon value[0], class:"c#{@group.check_color}"
           	span class="c#{@group.check_color}" #{value[1].titleize.upcase}
          ul.dropdown-menu.menu-user
            = link_to group_path(@group, view: view, order_sort: 'best'), remote: true do
	            li.dropdown-item.box-option-user
		          	span.icon-profile = fa_icon "rocket"
		           	span Best
            = link_to group_path(@group, view: view, order_sort: 'new'), remote: true  do
	            li.dropdown-item.box-option-user
		          		span.icon-profile = fa_icon "star"
		           		span NEW
		    = link_to group_path(@group, view: view, order_sort: 'most_commentted'), remote: true  do
	            li.dropdown-item.box-option-user
	          		span.icon-profile = fa_icon "fire"
	           		span MOST COMMENTTED
            = link_to group_path(@group, view: view, order_sort: 'most_voted'), remote: true  do
		        li.dropdown-item.box-option-user
		          		span.icon-profile = fa_icon "thumbs-up"
		           		span MOST VOTED
    	span style="margin-left: 30px;"
    	= render partial: "home/subject"

app/views/groups/_tools.html.slim
.group-tool
	.tool-title
		= fa_icon 'sun-o', class:"mr5"
		span.s12 QUEUES
	= link_to edit_group_path(@group, option: :mod_queue), remote: true, class: 'c_gray' do
		.tool-option.p6#mod_queue.group-focus Mod queue
        = link_to edit_group_path(@group, option: :unpprove_posts), remote: true, remote: true, class: 'c_gray' do
          .tool-option.p6#unpprove_posts Unpprove posts
	= link_to edit_group_path(@group, option: :report), remote: true, class: 'c_gray' do
		.tool-option.p6#report Report
	.tool-title
		= fa_icon 'user', class:"mr5"
		span.s12 USER MANAGEMENT
	= link_to edit_group_path(@group, option: :members), remote: true, class: 'c_gray' do
		.tool-option.p6#members Members
	= link_to edit_group_path(@group, option: :approved), remote: true, class: 'c_gray' do
		.tool-option.p6#approved Unpprove members
	= link_to edit_group_path(@group, option: :banned), remote: true, class: 'c_gray' do
		.tool-option.p6#banned Banned members
	= link_to edit_group_path(@group, option: :muted), remote: true, class: 'c_gray' do
		.tool-option.p6#muted Muted members

app/views/groups/_user_approve.html.slim
.container-fluid
  .row
    .col-md-1
    .col-md-10
    	.mod-header
    		span User Unapprovement
        br
    	.chec-box-list.white.mb10.display-flex
	    	= check_box :all, nil, class:'bigger-checkbox m10'
	    	.tmol.mr10 = fa_icon 'sort-desc'
            #tool-option.display-flex.display-none
    	    	.approve.tmol.mr10
    	    		.mr5 = fa_icon 'check'
    	    		span.s12.tb700 Approve
    	    	.remove.tmol.mr10
    	    		.mr5 = fa_icon 'trash'
    	    		span.s12.tb700 Remove
    	    	.remove.tmol.mr10
    	    		.mr5 = fa_icon 'window-close'
    	    		span.s12.tb700 Spam
	    = render partial: 'list_user', locals: {persons: @unapprove_members}
    .col-md-1

app/views/groups/edit.html.slim
.container-fluid
  .row
    .col-md-2._f6f7f8.h100.p0
    	= render partial: 'tools', locals: {group: @group}
    .col-md-10#view-group
    	= render partial: 'mod_queue', local: {group: @group, posts: @posts, view: "large"}
javascript:
 Group.run()
 GroupTools.run()

app/views/groups/index.js.erb
<%case params[:view]%>
<%when "posts"%>
	$("#view-group").html("<%=j render :partial => 'home/index', :locals => { posts: @posts } %>");
	$(".sort-bar-header").removeClass("de-active")
	$(".group-option").css("marginBottom", "0")
<%when "about"%>
	$("#view-group").html("<%=j render :partial => 'groups/group_about', :locals => { group: @group } %>");
	$(".sort-bar-header").addClass("de-active")
	$(".group-option").css("marginBottom", "20px")
<%when "members"%>
	$("#view-group").html("<%=j render :partial => 'groups/group_members', :locals => { group: @group } %>");
	$(".sort-bar-header").addClass("de-active")
	$(".group-option").css("marginBottom", "20px")
<%end%>
<%if params[:order_sort]%>
	$(".sort-bar-header").html("<%=j render :partial => 'sort_bar', :locals => {view: 'large', order_sort: params[:order_sort]} %>");
	$("#view-group").html("<%=j render :partial => 'home/index', :locals => { posts: @posts, order_sort: params[:order_sort]} %>");	
<%end%>

app/views/groups/new.html.slim
.container
  .row
    .col-md-8.center-block
      = render "new", locals: {group: @group}
    .col-md-4