config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'groups/index'
  get 'groups/show'
  get 'groups/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  devise_for :persons, :controllers => {sessions: "sessions"}

  resources :persons do
    resources :groups
  end

  resources :groups do
    resources :posts
    member do
      post :join
      delete :leave
      post :user_approved
      post :user_banned
      post :user_muted
      post :manage_user
      post :post_approved
      post :post_unreport
    end
  end

  resources :persons do
  	resources :posts
    member do
      get 'profile'
      get 'overview'
      get 'comments'
      get 'saved'
      get 'saved'
      get 'hidden'
      get 'upvoted'
      get 'upvoted'
      get 'downvoted'
      get 'all_settings'
      get 'account'
      post 'account_setting'
      get 'person_profile'
      post 'profile_setting'
      get 'feed'
      post 'feed_setting'
      post 'follow'
      post "post_options"
      post 'report_post'
    end
  end

  resources :posts do
  	resources :comments
    member do
      post 'vote'
    end
  end

  resources :posts do
    resources :comments
  end

  resources :comments do
    member do
      post 'vote'
      post 'report'
    end
    collection do
      post "reply"
    end
  end

  resources :replies do
    member do
      post 'vote'
    end
  end

  get "/search", to: "home#search"
  get "/alert", to: "home#alert"
  get "/list_categories", to: "home#list_categories"

  namespace :admin do
    devise_for :admins, skip: :registrations
    root to: "admins#index"
    resources :persons, only: [:index, :show, :destroy] do
      collection do
        get 'person_index'
      end
    end
    resources :groups, only: [:index, :show, :destroy] do
      collection do
        get 'group_index'
      end
    end
    resources :posts, only: [:index, :show, :destroy] do
      collection do
        get 'post_index'
      end
    end
    resources :comments, only: [:index, :show, :destroy] do
      collection do
        get 'comment_index'
      end
    end
    resources :categories do
      collection do
        get 'category_index'
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@person = Person.all
		@groups = Group.all
	    @private_groups = Group.where(type: :private)
	    # get post
	    @posts = Post.all.where(post_creation: false)
	    # remove private posts
		@posts = @posts.to_a - @private_groups.posts

	  	if current_person
	  		@hidden_post = current_person.posts_hidden
	  		@posts = @posts.to_a - @hidden_post.to_a
	  	end
	  	case params[:order_sort]
	  	when 'new'
	  		@posts = @posts.sort { |x, y | y.created_at <=> x.created_at }
	  	when 'most_commentted'
	  		@posts = @posts.sort { |x, y | y.comments.count <=> x.comments.count }	
	  	when 'most_voted'
	  		@posts = @posts.sort { |x, y | x.total_votes <=> y.total_votes }
	  	else
	  		@posts = @posts.sort { |x, y | y.best_post? <=> x.best_post? }
  		end	
		if params[:subject]
			@posts = @posts.select { |x| x.category && x.category.title == params[:subject] }
		end

		respond_to do |format|
  			format.html
  			format.js
    	end
	end

	def search
		return unless params[:search]
		@groups = Group.where(['group_name LIKE ?', "%#{params[:search]}%"])
		@posts = Post.all
		respond_to do |format|
  			format.html
  			format.js
    	end
	end
  def alert
    @message = params[:message]
    respond_to do |format|
        format.html
        format.js
      end
  end

  def list_categories
  	@list_categories = Category.all
  end
end

app/views/home/_alert.html.slim
.popup.tc.animated.bounceInUp
  .message.tc
    .message-box
       span = alert

app/views/home/_create_post.html.slim
.box-create
	.box-image
	.box-title
	.box-content
		p  The best posts on Health Social for you, pulled from the most active communities on Health Social. Check here to see the most shared, upvoted, and commented content on the internet.
	.box-btn
		- if current_person
			= link_to "Create post", new_person_post_path(current_person), class: "btn btn-success btn-create-post"
      		= link_to "Create Community", new_person_group_path(current_person), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-create-group'}

app/views/home/_footer.html.slim
.box-footer
	.box-extend
		table
			tr
				td
					= link_to "About", root_path()
				td
					= link_to "Advertise", root_path()
				td
					= link_to "Health App", root_path()
			tr
				td
					= link_to "Careers", root_path()
				td
					= link_to "Blog", root_path()
				td
					= link_to "Press", root_path()
			tr
				td
					= link_to "Help", root_path()
				td
					= link_to "Gift", root_path()
				td
					= link_to "VIP", root_path()
	.box-license
		.policy
			span Content Policy
			span | 
			span Mod Policy
		.copyright
			p © 2019 Health, Inc. All rights reserved

app/views/home/_index.html.slim
- @posts.each do |post|
  - reported = post.belong_to && (post.belong_to.author == current_person) && post.reports.present?
  span.display-block.box-click id="#{post.author ? person_post_path(post.author, post) : ''}"
    .post-box.post-box-index id="#{post.id}" class="#{reported ? 'post-reported' : ""}"
      .post-voted
        - if current_person
          = link_to vote_post_path(post, vote: :upvote, view: "index"), method: :post, remote: true do
            = fa_icon "arrow-up", class:"#{post.upvote.include?(current_person) ? 'upvoted' : ""}"
          span.tc.vote-number = post.votes
          = link_to vote_post_path(post, vote: :downvote, view: "index"), method: :post, remote: true do
            = fa_icon "arrow-down", class:"#{post.downvote.include?(current_person) ? 'downvoted' : ""}"
        - else
          = link_to alert_path(message: "You need sign up first to vote this post!"), remote: true do
            = fa_icon "arrow-up"
          span.tc.vote-number = post.votes
          = link_to alert_path(message: "You need sign up first to vote this post!"), remote: true do
            = fa_icon "arrow-down"
      .row
        .col-md-9.p0.tmol
          .post-header-index.display-flex
            - if post.belong_to.present?
              = link_to group_path(post.belong_to), class:'post-group display-flex unset-text tmol' do
                .group-icon.mr5
                  = image_tag  post.belong_to.icon_url if post.belong_to.icon.present?
                .title.il.s12.tb.mr5.black = post.belong_to.group_name
            span.s12.tmol.mr5 Posted by
            .post-author
              - if current_person
                .user.user-email = link_to post.author.email, overview_person_path(post.author), class: "c_gray"
              - else
                = link_to alert_path(message: "You need sign up first to view user profile!"), remote: true do
                  .user.user-email.c_gray = post.author.email
            span.tmol.s12.c_gray = post.to_pretty
            - if post.belong_to&.type.in?([:private, :restricted]) && !reported
              span.tmol.s12.c_gray.ml5
                = fa_icon "check", class:"c_28a745"
                span.c_28a745 Approved
            - elsif reported
              span.tmol.s12.ml5.reported
                = fa_icon "flag"
                span.ml5 Reported
        .col-md-3
          - if person_signed_in?
            - if post.belong_to.present?
              - if post.belong_to.members.include?(current_person)
                = link_to leave_group_path(post.belong_to), method: :delete, remote: true, class:'btn float-right btn-leave-small de-active' do
                  = fa_icon 'check'
              - elsif post.belong_to.unapprove_members.include?(current_person)
                = link_to "SENDED", join_group_path(post.belong_to), method: :post, remote:true, class: "btn float-right btn-join-small #{post.belong_to.id} s10"
              - else
                = link_to join_group_path(post.belong_to), method: :post, remote: true, class:"btn float-right btn-join-small #{post.belong_to.id} s10" do
                  = fa_icon 'plus', class:'c_white mr5'
                  span JOIN
          - else
            = link_to person_session_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class:'btn float-right btn-join-small-login s10'} do
              = fa_icon 'plus', class:'c_white mr5'
              span JOIN

      .post-content
        - if post.is_question
          .category-post.il class="b_f0ad4e"
            span.c_white Question
        - if post.category
          .category-post.il class="#{post.category.color}"
            = post.category.title.capitalize
        .post-title.mb10
          = post.title
        .mb10 = post.content
        - if post.image.present?
          .post-image
            = image_tag post.image_url
      = render partial: 'home/post_option', locals: {post: post}

app/views/home/_post_option.html.slim
.post-option
  .comment.option-style
    = link_to person_post_path(post.author, post) do
      span = fa_icon "comment"
      span = post.display_comments
  - unless post.belong_to&.type == :private
    .share.option-style
      span = fa_icon "share"
      span Share
  - if post.author == current_person
    = link_to edit_person_post_path(current_person, post), method: :get do
      .edit-post.option-style
        span = fa_icon "pencil"
        span Edit Post
  .save.option-style
    - if person_signed_in?
      = link_to post_options_person_path(current_person, post_id: post.id, option: "save"), method: :post, remote: true do
        - if current_person.posts_saved.include?(post)
          span = fa_icon "bookmark", class:'c_cornflowerblue'
          span#save-post.c_cornflowerblue Unsave
        - else
          span = fa_icon "bookmark"
          span#save-post Save
    - else
      = link_to person_session_path(), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} do
        span = fa_icon "bookmark"
        span#save-post.login Save
  .hide.option-style
    - if person_signed_in?
      = link_to post_options_person_path(current_person, post_id: post.id, option: "hide"), method: :post, remote: true do
        span#hidden-post = fa_icon "ban"
        span = current_person.posts_hidden.include?(post) ?  'Unhide' : 'Hide'
    - else
      = link_to person_session_path(), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} do
        span#hidden-post = fa_icon "ban"
        span Hide
  - if person_signed_in? && current_person == post.author
    .delete.option-style
      = link_to post_options_person_path(current_person, post_id: post.id, option: "delete"), data: {confirm: "Are you sure?"}, method: :post, remote: true do
        span#hidden-post = fa_icon "trash"
        span Delete

  - if person_signed_in?
    .report-post.option-style data-url="#{report_post_person_path(current_person, post_id: post.id)}"
      span#report-post = fa_icon "flag"
      span Report

  - if person_signed_in? && post.belong_to && (current_person == post.belong_to.author)
    .approve.option-style
      = link_to post_unreport_group_path(post.belong_to, post_id: post.id), method: :post do
        span  = fa_icon 'check'
        span Approve

app/views/home/_report.html.slim
.modal-withdraw-transaction.modal
  .modal-dialog.modal-sm
    .modal-content
      .modal-title
      .modal-body
        .modal-body-content
          .header Report post
          hr
        .title.mb10 We're sorry something's wrong. How can we help?
        = form_tag '#', method: :post, class: "modal-report-post", id: "report-post"
          = hidden_field_tag :authenticity_token, form_authenticity_token
          .report-option
            = radio_button_tag :report, 0, checked: true
            span.ml5 It's a Spam
          .report-option
            = radio_button_tag :report, 1
            span.ml5 It infringes my copyright
          .report-option
            = radio_button_tag :report, 2
            span.ml5 It's targeted harassment
          .report-option
            = radio_button_tag :report, 3
            span.ml5 It's rude, vulgar or offensive
          .report-option
            = radio_button_tag :report, 4
            span.ml5 It's sexual or suggestive content involving minors
          .report-option
            = radio_button_tag :report, 5
            span.ml5 Other Reason
          .report-option
            = text_field_tag :reason_report, nil, class:"form-control", placeholder: "Please tell us your thinking!", required: true
          br
          .group-button-actions
            = submit_tag "Report", type: :button, class: 'btn btn-success button-report float-right'
            = button_tag "Cancel", type: :button, class: 'btn btn-create-group btn-cancel-report float-right mr5', 'data-dismiss': 'modal'

app/views/home/_search_best_result.html.slim
.search-result
	- groups.each do |group|
		.row.mb10
    		.col-md-3
	    		.group-box-info.tmol
		    		.group-icon.mr5
		            	= image_tag  group.icon_url if  group.icon.present?
			      	.communinty
                        - if group.type == :private && !group.members.include?(current_person)
                            = link_to alert_path(message: "This group is private. You need to join first!"), remote: true, class:'post-group unset-text tmol' do
                                .title.il.s12.mr5.black.tb700 = group.group_name
                                - if group.type == :private
                                  = fa_icon 'lock' , class:'c_fd7e14'
                                - elsif group.type == :public
                                  = fa_icon 'user' , class:'c_17a2b8'
                                - else
                                  = fa_icon 'eye' , class:'c_104939'
                        - else
    			      		= link_to group_path(group), class:'post-group unset-text tmol' do
    			        		.title.il.s12.mr5.black.tb700 = group.group_name
                                - if group.type == :private
                                  = fa_icon 'lock' , class:'c_fd7e14'
                                - elsif group.type == :public
                                  = fa_icon 'user' , class:'c_17a2b8'
                                - else
                                  = fa_icon 'eye' , class:'c_104939'
			        	.title.il.s12.mr5.black = t('group.members', members: group.members.count)
    		.col-md-7
    			.group-description.s12.c_gray
    				= group.about
		    .col-md-2
		      .il.pull-right style="width: 85%"
                - if person_signed_in?
                      - if group.members.include?(current_person)
                        = link_to "JOINED", leave_group_path(group), method: :delete , remote: true, class: "btn btn-joined  btn-leave-small tmol mb0"
                      - elsif group.unapprove_members.include?(current_person)
                        = link_to "SENDED", join_group_path(group), method: :post, remote:true, class: "btn btn-join-small s12"
                      - else
                        = link_to "JOIN", join_group_path(group), method: :post, remote: true, class: "btn btn-join-small s12"
                - else
                  = link_to "JOIN", person_session_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class:'btn btn-join-small-login s12'}
.search-post
  = render partial: "list_posts_search", locals: {posts: @posts}

app/views/home/_sort_bar_index.html.slim
.sort-bar-header
	.sort-bar.tmol
		span VIEW
		= link_to root_path(view: "large", order_sort: order_sort), remote: true do
			- if params[:view].present?
				- active = "#{params[:view] == 'large' ? '_0079d3' : 'gray'}"
			- else
				- active = '_0079d3'
			.view-large
				table
					tr.line-split class="#{active}"
						td
					tr class="#{active}"
						td
		= link_to root_path(view: "medium", order_sort: order_sort), remote: true do
			- active = "#{params[:view] == 'medium' ? '_0079d3' : 'gray'}"
			.view-medium
				table
					tr.line-split class="#{active}"
						td
					tr.line-split class="#{active}"
						td
					tr class="#{active}"
						td
		span style="margin-left: 30px;" SORT
		.btn-group#group-sort-btn
          button.btn.dropdown-toggle.user-info data-toggle="dropdown"
          	- order = order_sort ? order_sort : 'best'
          	- value = SORT_PARAMS[order.to_sym]
          	span.icon-profile = fa_icon value[0], class:"c_0079d3 "
           	span.c_0079d3 #{value[1].titleize.upcase}
          ul.dropdown-menu.menu-user
            = link_to root_path(view: view, order_sort: 'best'), remote: true do
	            li.dropdown-item.box-option-user
		          	span.icon-profile = fa_icon "rocket"
		           	span Best
            = link_to root_path(view: view, order_sort: 'new'), remote: true  do
	            li.dropdown-item.box-option-user
		          		span.icon-profile = fa_icon "star"
		           		span NEW
		    = link_to root_path(view: view, order_sort: 'most_commentted'), remote: true  do
	            li.dropdown-item.box-option-user
	          		span.icon-profile = fa_icon "fire"
	           		span Most Commentted
            = link_to root_path(view: view, order_sort: 'most_voted'), remote: true  do
		        li.dropdown-item.box-option-user
		          		span.icon-profile = fa_icon "thumbs-up"
		           		span Most Voted
    	span style="margin-left: 30px;"
    	= render partial: "home/subject"

app/views/home/_subject.html.slim
.list-subject.tmol
	- list_category.each do |c|
	    = link_to root_path(subject: c.title), class: "text-decoration-none", remote: true do
			.subject.subject-style class="#{c.color}"
					span = c.title
					.s10.tc = "#{c.posts_to_pretty}"
	.see-more-subject._17a2b8
		= link_to "View More >>", list_categories_path()

app/views/home/alert.js.erb
$("#alert").html("<%=j render :partial => 'home/alert', locals: {alert: @message} %>");
setTimeout((function() {
  $("#alert .popup").addClass("bounceOutDown");
}), 5000)

app/views/home/index.html.slim
= render partial: 'sort_bar_index', locals: {view: 'large', order_sort: 'best'}
.container
  .row
    .col-md-9#home-index
      = render partial: "index", locals: {posts: @posts}
      = render partial: "home/report"
    .col-md-3
      = render "home/create_post"
      = render "home/trending_communities", locals: {groups: @groups}
      = render "home/footer"
javascript:
 Group.run()
 Index.run()

app/views/home/list_categories.html.slim
.container
  .row
    .col-md-9#home-index
  		= render partial: "list_categories", locals: {categories: @list_categories}
    .col-md-3
      = render "home/footer"
javascript:
 Group.run()
 Index.run()

app/views/home/search.html.slim
.search-header
	.param-search-header
		= params[:search]
	span.s12 Search results
.search-option.tmol
	= link_to search_path(view: 'best_result', search: params[:search]), remote: true do
		.search-option-style.best-result.focus
			span Best Result
	= link_to search_path(view: 'posts', search: params[:search]), remote: true do
		.search-option-style.posts-result
			span Posts
	= link_to search_path(view: 'communities', search: params[:search]), remote: true do
		.search-option-style.group-users-result
			span Communities and Users
.container-fluid
  .row
    .col-md-9#search-index
     	= render partial: "search_best_result", locals: {groups: @groups, posts: @posts}
    .col-md-3
javascript:
 Group.run()
 Index.run()

app/views/home/search.js.erb
<%if params[:view] == 'posts'%>
	$("#search-index").html("<%=j render :partial => 'home/list_posts_search', :locals => { posts: @posts } %>");
<%elsif params[:view] == 'communities'%>	
	$("#search-index").html("<%=j render :partial => 'home/search_best_result', :locals => {groups: @groups } %>");
<%else %>	
	$("#search-index .search-group").html("<%=j render :partial => 'home/search_best_result', :locals => { groups: @groups} %>");
	$("#search-index .search-post").html("<%=j render :partial => 'home/list_posts_search', :locals => { posts: @posts } %>");
<%end%>