config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'groups/index'
  get 'groups/show'
  get 'groups/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  devise_for :persons, :controllers => {sessions: "sessions"}

  resources :persons do
    resources :groups
  end

  resources :groups do
    resources :posts
    member do
      post :join
      delete :leave
      post :user_approved
      post :user_banned
      post :user_muted
      post :manage_user
      post :post_approved
      post :post_unreport
    end
  end

  resources :persons do
  	resources :posts
    member do
      get 'profile'
      get 'overview'
      get 'comments'
      get 'saved'
      get 'saved'
      get 'hidden'
      get 'upvoted'
      get 'upvoted'
      get 'downvoted'
      get 'all_settings'
      get 'account'
      post 'account_setting'
      get 'person_profile'
      post 'profile_setting'
      get 'feed'
      post 'feed_setting'
      post 'follow'
      post "post_options"
      post 'report_post'
    end
  end

  resources :posts do
  	resources :comments
    member do
      post 'vote'
    end
  end

  resources :posts do
    resources :comments
  end

  resources :comments do
    member do
      post 'vote'
      post 'report'
    end
    collection do
      post "reply"
    end
  end

  resources :replies do
    member do
      post 'vote'
    end
  end

  get "/search", to: "home#search"
  get "/alert", to: "home#alert"
  get "/list_categories", to: "home#list_categories"

  namespace :admin do
    devise_for :admins, skip: :registrations
    root to: "admins#index"
    resources :persons, only: [:index, :show, :destroy] do
      collection do
        get 'person_index'
      end
    end
    resources :groups, only: [:index, :show, :destroy] do
      collection do
        get 'group_index'
      end
    end
    resources :posts, only: [:index, :show, :destroy] do
      collection do
        get 'post_index'
      end
    end
    resources :comments, only: [:index, :show, :destroy] do
      collection do
        get 'comment_index'
      end
    end
    resources :categories do
      collection do
        get 'category_index'
      end
    end
  end
end

app/models/post.rb
class Post
	include Neo4j::ActiveNode

	# property :posts_id, auto: :uuid
	property :title, type: String
	property :content, type: String
	property :image, type: String
	mount_uploader :image, ImageUploader
	property :created_at, type: DateTime
	property :updated_at, type: DateTime
	property :upvotes, type: Integer,  default: 0
	property :downvotes, type: Integer,  default: 0
	property :post_creation, type: Boolean,  default: false
	property :is_question, type: Boolean,  default: false

	id_property :id, auto: :uuid

	has_many :in, :comments, origin: :post, dependent: :destroy
	has_one :out, :author, type: :author, model_class: :Person
	has_one :out, :category, type: :type_category, model_class: :Category
	has_one :out, :belong_to, type: :belong_to, model_class: :Group
	has_many :in, :upvote, type: :upvoted_by, model_class: :Person
	has_many :in, :downvote, type: :downvoted_by, model_class: :Person
  has_many :in, :reports, type: :have_report, model_class: :Report

	def best_post?
		self.upvotes + self.comments.count
	end

  	def votes
    	self.upvotes - self.downvotes
  	end

  	def total_votes
		self.upvotes + self.downvotes
  	end

	def controversial
		self.upvotes - self.downvotes
	end

	def to_pretty
    	a = (Time.now-self.created_at).to_i
	    case a
	      when 0 then 'just now'
	      when 1 then 'a second ago'
	      when 2..59 then a.to_s+' seconds ago'
	      when 60..119 then 'a minute ago' #120 = 2 minutes
	      when 120..3540 then (a/60).to_i.to_s+' minutes ago'
	      when 3541..7100 then 'an hour ago' # 3600 = 1 hour
	      when 7101..82800 then ((a+99)/3600).to_i.to_s+' hours ago'
	      when 82801..172000 then 'a day ago' # 86400 = 1 day
	      when 172001..518400 then ((a+800)/(60*60*24)).to_i.to_s+' days ago'
	      when 518400..1036800 then 'a week ago'
	      else ((a+180000)/(60*60*24*7)).to_i.to_s+' weeks ago'
	    end
	end

  def display_comments
    if self.comments.count < 1
      "0"
    elsif self.comments.count == 1
      "1 Comment"
    else
      "#{self.comments.count} Comments"
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :get_post
  def index
    page = params[:page] ? (params[:page].to_i * 25) : 25
    @posts = Post.all
    @load_more = @posts.length > page ? true : false
    @posts = @posts.limit(page)
  end

  def show
  end

  def post_index
    page = params[:page] ? (params[:page].to_i * 25) : 25
    if params[:person_id]
      @person = Person.find_by(id: params[:person_id])
      @all_posts = @person.posts
      @header = @person.full_name
    elsif params[:group_id]
      @group = Group.find_by(id: params[:group_id])
      @all_posts = @group.posts
      @header = "#{@group.group_name} Community"
    end
    @load_more = @all_posts.length > page ? true : false
    @posts = @all_posts.limit(page)
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_path()
  end

  private
  def get_post
    return if params[:id].nil?
    @post = Post.find_by(id: params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :get_group, :get_post, :get_user, :get_category
	def index
		@posts = @person.posts.all.order(updated_at: :asc).page(1).per 10
		# @post = Post.find(params[:id])
		# @time = Time.now.min - @post.created_at.min
	end

	def show
		@post = Post.find(params[:id])
		@comment = @post.comments.new
    @list_post_comments = @post.comments.where(type: :comment)
		@new_reply = Comment.new
	end

	def new
		@post = current_person.posts.new
	end

	def create
		@post = Post.create!(post_params)
		@post.image = post_params[:image] unless post_params[:image].nil?
    @post.upvotes += 1
    @post.upvote << current_person
  	@post.save!
  	current_person.posts << @post

		if @group
      if @group.type.in?([:private, :restricted])
        @group.unapprove_posts << @post
      else
        @group.posts << @post
      end
		end
    if @category
      @post.category = @category
      @category.posts << @post
    end

    if @group
		  redirect_to group_path(@group)
    else
      redirect_to overview_person_path(current_person)
    end
	end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update!(post_params.to_h)
    @post.category.posts.delete(@post) if @post.category
    if @category
      @post.category = @category
      @category.posts << @post
      @post.save
    end
    redirect_to overview_person_path(current_person)
  end

  def vote
    return unless params[:vote]
    @view = "index" if params[:view] == 'index'
    if @post.upvote.include?(current_person) || @post.downvote.include?(current_person)
      if @post.upvote.include?(current_person) && params[:vote] == "downvote"
          # post
          @post.upvotes -= 1
          @post.upvote.delete(current_person)
          @post.downvotes += 1
          @post.downvote << current_person
          @color = 'purple'
          # person
          current_person.upvote.delete(@post)
          current_person.downvote<< @post
        elsif @post.downvote.include?(current_person) && params[:vote] == "upvote"
          @post.downvotes -= 1
          @post.downvote.delete(current_person)
          @post.upvotes += 1
          @post.upvote << current_person
          # person
          current_person.upvote << @post
          current_person.downvote.delete(@post)
          @color = "red"
        elsif @post.upvote.include?(current_person) && params[:vote] == "upvote"
          @post.upvotes -= 1
          @post.upvote.delete(current_person)
          current_person.upvote.delete(@post)
          @color = "none"
        else
          @post.downvotes -= 1
          @post.downvote.delete(current_person)
          current_person.downvote.delete(@post)
          @color = "none"
      end
    else
      if params[:vote] == "upvote"
        @post.upvotes += 1
        @post.upvote << current_person
        current_person.upvote << @post
        @color = "red"
      else
        @post.downvotes += 1
        @post.downvote << current_person
        current_person.downvote << @post
        @color = 'purple'
      end
    end
    @view = "index"
    @post.save!
    current_person.save!
    respond_to do |format|
      format.html
      format.js
    end
  end

	private
  def get_category
    return unless params[:post]
    @category = Category.find_by(id: params[:post][:category])
  end
	def get_group
		return if params[:group_id ].nil?
		@group = Group.find(params[:group_id ])
	end
  def get_post
    return if params[:id ].nil?
    @post = Post.find(params[:id ])
  end

	def post_params
		params.require(:post).permit(:title, :content, :image, :is_question)
	end

  def get_user
    return unless params[:person_id]
    @person = Person.find(params[:person_id])
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_empty_things.html.slim
.empty
  .description
    = fa_icon "comments" , class: "mb10"
    .s18.tb700.c_gray No Comments Yet
    .s14.c_gray Be the first to share what you think!

app/views/posts/_index.html.slim
- @posts.each do |post|
  .post-box.post-box-index
    .post-voted
      .up-vote.tc data-url="#{vote_post_path(post, vote: :upvote)}"
        = fa_icon "arrow-up", class:"#{post.upvote.include?(current_person) ? 'upvoted' : ""}"
      span.tc.vote-number = post.votes
      .down-vote.tc data-url="#{vote_post_path(post, vote: :downvote)}"
        = fa_icon "arrow-down", class:"#{post.downvote.include?(current_person) ? 'downvoted' : ""}"
    .row
      .col-md-9.p0.tmol
        .post-header-index.display-flex
          - if post.belong_to.present?
            = link_to group_path(post.belong_to), class:'post-group display-flex unset-text tmol' do 
              .group-icon.mr5
                = image_tag  post.belong_to.icon_url if post.belong_to.icon.present? 
              .title.il.s12.tb.mr5.black = post.belong_to.group_name
          span.s12.tmol.mr5 Posted by
          .post-author
            .user.user-email = link_to post.author.email, overview_person_path(post.author), class: "c_gray"
          span.tmol.s12.c_gray = post.to_pretty
      .col-md-3
        - if post.belong_to.present?
          - if !post.belong_to.members.include?(current_person)
            = link_to join_group_path(post.belong_to), method: :post, remote: true, class:'btn float-right btn-join-small s10' do
              = fa_icon 'plus', class:'c_white mr5'
              span JOIN
            = link_to leave_group_path(post.belong_to), method: :delete, remote: true, class:'btn float-right btn-leave-small de-active' do
              = fa_icon 'check'

    .post-content
      .post-title.mb10
        = post.title
      .mb10 = post.content
      - if post.image.present?
        .post-image
          = image_tag post.image_url
    = render partial: 'home/post_option', locals: {post: post}

app/views/posts/_new.html.slim
- if @group.nil?
	- url = @post.id ? person_posts_path(current_person, @post.id) : person_posts_path(current_person)
- else
	- @url = group_posts_path(@group)
h5 Create a Post
hr
.sort-group
	= render partial: 'posts/sort_group_for_post', locals: {view: 'large', order_sort: 'best'}
.new-post
	.btn-group role="group" aria-label="..."
		button.btn.btn-post.btn-post-type type="button"
      		span.post-icon-option = fa_icon "book"
      		span.post-type Post
		button.btn.btn-video.btn-post-type type="button"
			span.post-icon-option = fa_icon "image"
      		span.post-type  Image & Video
		button.btn.btn-link.btn-post-type type="button"
			span.post-icon-option = fa_icon "link"
      		span.post-type Link
	#post-box
		.form-box
			= form_for @post, url: @url do |f|
				.post-option.tmol
        			.form-category.mr5
          				= f.select :category, category_options, selected: @post.category && @post.category.id , include_blank: "Choose a Category"
					.form-group.action-for-post 
						.more-option-post
							- if @post.is_question
								button.btn.btn-oc#question-btn.is_question type="button" title="Unmark Question"
									span.post-icon-option.mr5 = fa_icon "check"
									span Question
									= hidden_field_tag 'post[is_question]', true, id: "is_question"
							- else
								button.btn.btn-oc#question-btn type="button" title="Mark as a question"
									span.post-icon-option.mr5 = fa_icon "plus"
									span Question
									= hidden_field_tag 'post[is_question]', false, id: "is_question"
				.form-group.form-title
					= f.text_field :title, class: "form-control", placeholder: 'Title', required: true
				.form-group.form-for-textarea
					.option-text-area.tmol
						span.post-icon-option title = "Bold" = fa_icon "bold"
						span.post-icon-option title = "Italic" = fa_icon "italic"
						span.post-icon-option title = "Link" = fa_icon "link"
						span.post-icon-option title = "Strikethrough" = fa_icon "strikethrough"
						span.post-icon-option title = "Code" = fa_icon "code"
						span.post-icon-option title = "Superscript" = fa_icon "superscript"
						span.post-icon-option title = "Spoiler" = fa_icon "exclamation-circle"
						span.post-icon-option title = "Header" = fa_icon "header"
						span.post-icon-option title = "Bullet list" = fa_icon "list-ul"
						span.post-icon-option title = "Number list" = fa_icon "list-ol"
						span.post-icon-option title = "Quote" = fa_icon "quote-left"
						span.post-icon-option title = "Table" = fa_icon "table"
						span.post-icon-option title = "Image" = fa_icon "image"
						span.post-icon-option title = "Video" = fa_icon "video-camera"
					.text-area-content
						= f.text_area :content, class: "form-control", placeholder: 'Text', required: true
				.form-group.action-for-post
					.more-option-post
						button.btn.btn-oc type="button"
							span.post-icon-option = fa_icon "plus"
							span OC
						button.btn.btn-oc type="button"
							span.post-icon-option = fa_icon "plus"
							span Spoiler
						button.btn.btn-oc type="button"
							span.post-icon-option = fa_icon "plus"
							span NSFW
						= f.submit "#{@post.id ? 'Update' : 'Create'}", class: "btn-create float-right"
						button.btn.btn-cancel type="button" Cancel
				= render "posts/sort_category_post"
				= render "posts/footer_create_post"
	#video-box
      .form-box
        = form_for @post, url: @url do |f|
			.post-option.tmol
    			.form-category.mr5
      				= f.select :category, category_options, selected: @post.category && @post.category.id , include_blank: "Choose a Category"
				.form-group.action-for-post 
					.more-option-post
						- if @post.is_question
							button.btn.btn-oc#question-btn.is_question type="button" title="Unmark Question"
								span.post-icon-option.mr5 = fa_icon "check"
								span Question
								= hidden_field_tag 'post[is_question]', true, id: "is_question"
						- else
							button.btn.btn-oc#question-btn type="button" title="Mark as a question"
								span.post-icon-option.mr5 = fa_icon "plus"
								span Question
								= hidden_field_tag 'post[is_question]', false, id: "is_question"

        	.form-group.form-title
            	= f.text_field :title, class: "form-control", placeholder: 'Title'
        	.form-group.upload-box
          		.upload
            		img id="image-background"
            		img id="preview"
	          		.upload-image.tmol
						span.post-icon-option.tmol = fa_icon "plus"
			        	= f.file_field :image, class: "form-control", placeholder: 'Text'
		    .form-group.action-for-post
					.more-option-post
						button.btn.btn-oc type="button"
							span.post-icon-option = fa_icon "plus"
							span OC
						button.btn.btn-oc type="button"
							span.post-icon-option = fa_icon "plus"
							span Spoiler
						button.btn.btn-oc type="button"
							span.post-icon-option = fa_icon "plus"
							span NSFW
						= f.submit "#{@post.id ? 'Update' : 'Create'}", class: "btn-create float-right"
						button.btn.btn-cancel type="button" Cancel
			= render "posts/footer_create_post"
	#link-box
		.form-box
			= form_for @post, url: @url do |f|
				.post-option.tmol
        			.form-category.mr5
          				= f.select :category, category_options, selected: @post.category && @post.category.id , include_blank: "Choose a Category"
					.form-group.action-for-post 
						.more-option-post
							- if @post.is_question
								button.btn.btn-oc#question-btn.is_question type="button" title="Unmark Question"
									span.post-icon-option.mr5 = fa_icon "check"
									span Question
									= hidden_field_tag 'post[is_question]', true, id: "is_question"
							- else
								button.btn.btn-oc#question-btn type="button" title="Mark as a question"
									span.post-icon-option.mr5 = fa_icon "plus"
									span Question
									= hidden_field_tag 'post[is_question]', false, id: "is_question"

				.form-group.form-title
					= f.text_field :title, class: "form-control", placeholder: 'Title'
				.form-group.form-for-textlink
					= f.text_area :content, class: "form-control", placeholder: 'Url'
				.form-group.action-for-post
					.more-option-post
						button.btn.btn-oc type="button"
							span.post-icon-option = fa_icon "plus"
							span OC
						button.btn.btn-oc type="button"
							span.post-icon-option = fa_icon "plus"
							span Spoiler
						button.btn.btn-oc type="button"
							span.post-icon-option = fa_icon "plus"
							span NSFW
						= f.submit "#{@post.id ? 'Update' : 'Create'}", class: "btn-create float-right"
						button.btn.btn-cancel type="button" Cancel
			= render "posts/footer_create_post"

app/views/posts/_post_content.html.slim
- reported = @post.belong_to && (@post.belong_to.author == current_person) && @post.reports.present?
.post-box id="#{@post.id}" class="#{reported ? 'post-reported' : ""}"
  .post-voted
    - if current_person
      = link_to vote_post_path(@post, vote: :upvote), method: :post, remote: true do
        = fa_icon "arrow-up", class:"#{@post.upvote.include?(current_person) ? 'upvoted' : ""}"
      span.tc.vote-number = @post.votes
      = link_to vote_post_path(@post, vote: :downvote), method: :post, remote: true do
        = fa_icon "arrow-down", class:"#{@post.downvote.include?(current_person) ? 'downvoted' : ""}"
    - else
      = link_to alert_path(message: "You need sign up first to vote this post!"), remote: true do
        = fa_icon "arrow-up"
      span.tc.vote-number = @post.votes
      = link_to alert_path(message: "You need sign up first to vote this post!"), remote: true do
        = fa_icon "arrow-down"
  .col-md-9.p0.tmol.mb10
    .post-header-index.display-flex
      - if @post.belong_to.present?
        = link_to group_path(@post.belong_to), class:'post-group display-flex unset-text tmol' do
          .group-icon.mr5
            = image_tag  @post.belong_to.icon_url if @post.belong_to.icon.present?
          .title.il.s12.tb.mr5.black = @post.belong_to.group_name
      span.s12.tmol.mr5 Posted by
      .post-author
        - if current_person
          .user.user-email = link_to @post.author.email, overview_person_path(@post.author), class: "c_gray"
        - else
          = link_to alert_path(message: "You need sign up first to view user profile!"), remote: true do
            .user.user-email.c_gray = @post.author.email
      span.tmol.s12.c_gray = @post.to_pretty
      - if @post.belong_to&.type.in?([:private, :restricted]) && !reported
        span.tmol.s12.c_gray.ml5
          = fa_icon "check", class:"c_28a745"
          span.c_28a745 Approved
      - elsif reported
        span.tmol.s12.ml5.reported
          = fa_icon "flag"
          span.ml5 Reported
  .post-content
    - if @post.is_question
      .category-post.il class="b_f0ad4e"
        span.c_white Question
    - if @post.category
      .category-post.il class="#{@post.category.color}"
        = @post.category.title.capitalize
  	.post-title.mb10
      = @post.title
      - if @post.image.present?
      	.post-image
          = link_to @post.image_url, target: :_blank do
        		= image_tag @post.image_url
      .s14.mb10.mt5 = @post.content
  = render partial: "home/post_option", locals:{post: @post}
  = render partial: "comments/new_comment", locals: {post: @post, comment: @comment }
  = render partial: "posts/sort_comments"
  .list-comment
    - if @post.comments.count == 0
      = render partial: "posts/empty_things"
    - else
        = render partial: "comments/list_comments", locals: {comments: @list_post_comments, new_reply: @new_reply}

app/views/posts/_post_details.html.slim
button.btn-post-infor
	span Like
button.btn-post-infor  
	span Share

app/views/posts/_post_header.html.slim
.post-header
  .user-summary
    .post-voted.il
      = link_to vote_post_path(@post, vote: :upvote), method: :post, remote: true do
        = fa_icon "arrow-up", class:"#{@post.upvote.include?(current_person) ? 'upvoted' : "" }"
      span.il.vote-number = @post.votes
      = link_to vote_post_path(@post, vote: :downvote), method: :post, remote: true do
        = fa_icon "arrow-down", class:"#{@post.downvote.include?(current_person) ? 'downvoted' : "" }"
    .post-header-title.il
      - if @post.image.present?
        = fa_icon "image"
      - else
        = fa_icon "file"
      .overlength
        span = @post.title
    .btn-close-post.pull-right.link-to
      = link_to root_path do
        span Close
        = fa_icon "times"

app/views/posts/_post_infor.html.slim
.post-infor
	.post-comment-infor
		span.post-comment-infor-content
		- if @post.comments.count > 1
			= @post.comments.count 
			|  Comments
		- else 
			= @post.comments.count 
			|  Comment
		button.btn-post-infor
			span Like
		button.btn-post-infor  
			span Share

app/views/posts/_sort_comments.html.slim
span.s12 SORT BY
.btn-group#group-sort-btn
  button.btn.dropdown-toggle.user-info data-toggle="dropdown"
    span.s14 Q&A(SUGGESTED)
  ul.dropdown-menu.menu-user
    li.dropdown-item.box-option-user
      span.s14 Best
    li.dropdown-item.box-option-user
      span.s14 New
    li.dropdown-item.box-option-user
      span.s14 Controversial
    li.dropdown-item.box-option-user
      span.s14 Top
    li.dropdown-item.box-option-user
      span.s14 Q&A(SUGGESTED)
hr.mt0

app/views/posts/_sort_group_for_post.html.slim
- if person_signed_in?

app/views/posts/create.html.slim
h1 Posts#create
p Find me in app/views/posts/create.html.slim

app/views/posts/index.html.slim
= render "persons/profile_bar"
.container-fluid.content-app
  .row
    .col-md-9.center-block
      = render partial: "posts/index", locals: {posts: @posts}
    .col-md-3
      = render "home/create_post"

app/views/posts/new.html.slim
- if @group.nil?
	- @url = person_posts_path(current_person)
- else
	- @url = group_posts_path(@group)

.container
  .row
    .col-md-9.center-block
      	h5 Create a Post
		hr
		.sort-group
        	= render partial: 'posts/sort_group_for_post', locals: {view: 'large', order_sort: 'best'}
		.new-post
			.btn-group role="group" aria-label="..."
				button.btn.btn-post.btn-post-type type="button"
              		span.post-icon-option = fa_icon "book"
              		span.post-type Post
				button.btn.btn-video.btn-post-type type="button"
					span.post-icon-option = fa_icon "image"
              		span.post-type  Image & Video
				button.btn.btn-link.btn-post-type type="button"
					span.post-icon-option = fa_icon "link"
              		span.post-type Link
			#post-box
				.form-box
					= form_for @post, url: @url do |f|
						.form-group.form-title
							= f.text_field :title, class: "form-control", placeholder: 'Title', required: true
						.form-group.form-for-textarea
							.option-text-area.tmol
								span.post-icon-option title = "Bold" = fa_icon "bold"
								span.post-icon-option title = "Italic" = fa_icon "italic"
								span.post-icon-option title = "Link" = fa_icon "link"
								span.post-icon-option title = "Strikethrough" = fa_icon "strikethrough"
								span.post-icon-option title = "Code" = fa_icon "code"
								span.post-icon-option title = "Superscript" = fa_icon "superscript"
								span.post-icon-option title = "Spoiler" = fa_icon "exclamation-circle"
								span.post-icon-option title = "Header" = fa_icon "header"
								span.post-icon-option title = "Bullet list" = fa_icon "list-ul"
								span.post-icon-option title = "Number list" = fa_icon "list-ol"
								span.post-icon-option title = "Quote" = fa_icon "quote-left"
								span.post-icon-option title = "Table" = fa_icon "table"
								span.post-icon-option title = "Image" = fa_icon "image"
								span.post-icon-option title = "Video" = fa_icon "video-camera"
							.text-area-content
								= f.text_area :content, class: "form-control", placeholder: 'Text', required: true
						.form-group.action-for-post
							.more-option-post
								button.btn.btn-oc type="button"
									span.post-icon-option = fa_icon "plus"
									span OC
								button.btn.btn-oc type="button"
									span.post-icon-option = fa_icon "plus"
									span Spoiler
								button.btn.btn-oc type="button"
									span.post-icon-option = fa_icon "plus"
									span NSFW
								= f.submit "Create", class: "btn-create"
								button.btn.btn-cancel type="button" Cancel
						= render "posts/sort_category_post"
						= render "posts/footer_create_post"
			#video-box
		      .form-box
		        = form_for @post, url: @url do |f|
		        	.form-group.form-title
		            	= f.text_field :title, class: "form-control", placeholder: 'Title'
		        	.form-group.upload-box
		          		.upload
                    		img id="image-background"
                    		img id="preview"
			          		.upload-image.tmol
								span.post-icon-option.tmol = fa_icon "plus"
					        	= f.file_field :image, class: "form-control", placeholder: 'Text'
				    .form-group.action-for-post
							.more-option-post
								button.btn.btn-oc type="button"
									span.post-icon-option = fa_icon "plus"
									span OC
								button.btn.btn-oc type="button"
									span.post-icon-option = fa_icon "plus"
									span Spoiler
								button.btn.btn-oc type="button"
									span.post-icon-option = fa_icon "plus"
									span NSFW
								= f.submit "Create", class: "btn-create"
								button.btn.btn-cancel type="button" Cancel
					= render "posts/footer_create_post"
			#link-box
				.form-box
					= form_for @post, url: @url do |f|
						.form-group.form-title
							= f.text_field :title, class: "form-control", placeholder: 'Title'
						.form-group.form-for-textlink
							= f.text_area :content, class: "form-control", placeholder: 'Url'
						.form-group.action-for-post
							.more-option-post
								button.btn.btn-oc type="button"
									span.post-icon-option = fa_icon "plus"
									span OC
								button.btn.btn-oc type="button"
									span.post-icon-option = fa_icon "plus"
									span Spoiler
								button.btn.btn-oc type="button"
									span.post-icon-option = fa_icon "plus"
									span NSFW
								= f.submit "Create", class: "btn-create"
								button.btn.btn-cancel type="button" Cancel
					= render "posts/footer_create_post"
    .col-md-3
      = render "home/create_post"


javascript:
	Post.run()

app/views/posts/show.html.slim
.container-fluid.post-container.content-app
  .container.post-box-content
    #post-header
      = render "post_header", locals: {post: @post}
    .row
      .col-md-9.center-block
        .post-form
        	= render "post_content", locals: {post: @post, comment: @comment, new_reply: @new_reply}
            = render partial: "home/report"
      .col-md-3
        - if @post.belong_to
          = render partial: "groups/group_info", locals: {group: @post.belong_to}
        - else
          - if @post.author == current_person
            = render "persons/user_box_info"
          - else
            = render partial: "persons/follow_box", locals: {person: @post.author}
        - if current_person
          = render partial: "groups/person_status", locals: {group: @post.belong_to}
        - if @post.belong_to && @post.belong_to.author == current_person && @post.reports.present?
          = render partial: "groups/post_status", locals: {post: @post}



javascript:
  ReplyComment.run()
  Group.run()

app/views/posts/vote.js.erb
$("#post-header").html("<%=j render :partial => 'posts/post_header', locals: {post: @post} %>");
<% if @view = "index" %>
  $("#<%= @post.id %>").find(".vote-number").text("<%= @post.votes%>");
  <% case @color %>
  <% when "red" %>
    $("#<%= @post.id %>").find(".downvoted").removeClass("downvoted");
    $("#<%= @post.id %>").find(".fa-arrow-up").addClass("upvoted");
    $("#<%= @post.id %>").find(".vote-number").addClass("upvoted");
  <% when "purple" %>
    $("#<%= @post.id %>").find(".upvoted").removeClass("upvoted")
    $("#<%= @post.id %>").find(".fa-arrow-down").addClass("downvoted");
    $("#<%= @post.id %>").find(".vote-number").addClass("downvoted");
  <% when "none" %>
    $("#<%= @post.id %>").find(".upvoted").removeClass("upvoted")
    $("#<%= @post.id %>").find(".downvoted").removeClass("downvoted");
  <% end %>
<% end %>